# generated by projio init
PYTHON ?= python
PROJIO ?= $(PYTHON) -m projio

.PHONY: projio-init projio-config-user projio-config-show projio-status projio-auth
.PHONY: projio-gh projio-gl projio-ria site-build site-serve mcp

projio-init:
	$(PROJIO) init .

projio-config-user:
	$(PROJIO) config init-user

projio-config-show:
	$(PROJIO) config -C . show

projio-status:
	$(PROJIO) status -C .

projio-auth:
	$(PROJIO) auth -C . doctor

projio-gh:
	$(PROJIO) sibling -C . github

projio-gl:
	$(PROJIO) sibling -C . gitlab

projio-ria:
	$(PROJIO) sibling -C . ria

site-build:
	$(PROJIO) site build -C .

site-serve:
	$(PROJIO) site serve -C .

mcp:
	$(PROJIO) mcp -C .


.PHONY: test build check publish-test publish clean

test:
	PYTHONPATH=src $(PYTHON) -m pytest tests -q

build:
	$(PYTHON) -m build

check:
	$(PYTHON) -m twine check dist/*

publish-test:
	$(PYTHON) -m twine upload --repository testpypi dist/*

publish:
	$(PYTHON) -m twine upload dist/*

clean:
	rm -rf build dist .pytest_cache .mypy_cache src/*.egg-info
