# generated by projio init
PYTHON ?= python
PROJIO ?= $(PYTHON) -m projio
NODE ?= node
NPM ?= npm
FRONTEND_DIR ?= frontend
DATA_PATH ?= data/demo_lfp.nc
HOST ?= 127.0.0.1
PORT ?= 8000
RESOURCE_NAME ?=
RESOURCE_URL ?=
DATALAD ?= datalad

.PHONY: projio-init projio-config-user projio-config-show projio-status projio-auth
.PHONY: projio-gh projio-gl projio-ria site-build site-serve mcp
.PHONY: help dev demo-data dev-ui kill-ui dev-api dev-web logs-api logs-web ui-status add-resource frontend-install frontend-dev frontend-build test build check publish-test publish clean

WEB_PORT ?= 5173

help:
	@printf '%s\n' \
		'make dev               # install editable package with dev extras' \
		'make demo-data         # generate a deterministic local demo dataset' \
		'make dev-ui            # start API + Vite in screen (kills stale first)' \
		'make kill-ui           # stop API + Vite and free ports' \
		'make logs-api          # attach to API screen session' \
		'make logs-web          # attach to frontend screen session' \
		'make ui-status         # check if API and frontend are listening' \
		'make add-resource RESOURCE_NAME=name RESOURCE_URL=git-url  # install a reference repo into resources/' \
		'make frontend-install  # install frontend dependencies' \
		'make frontend-dev      # run Vite dev server' \
		'make frontend-build    # build the frontend bundle' \
		'make test              # run python tests' \
		'make build             # build wheel and sdist' \
		'make check             # run twine check on dist artifacts' \
		'make clean             # remove local build artifacts and caches' \
		'make projio-status     # show projio status'

dev:
	$(PYTHON) -m pip install -e ".[dev]"

demo-data:
	PYTHONPATH=src $(PYTHON) scripts/generate_demo_data.py --output "$(DATA_PATH)"

kill-ui:
	-@screen -S tensorscope-api -X quit 2>/dev/null || true
	-@screen -S tensorscope-web -X quit 2>/dev/null || true
	-@fuser -k $(PORT)/tcp 2>/dev/null || true
	-@fuser -k $(WEB_PORT)/tcp 2>/dev/null || true

dev-api:
	@screen -dmS tensorscope-api sh -c \
		'PYTHONPATH=src $(PYTHON) -m tensorscope.cli serve "$(DATA_PATH)" --host "$(HOST)" --port "$(PORT)"'
	@echo "API: http://$(HOST):$(PORT)"

dev-web:
	@screen -dmS tensorscope-web sh -c \
		'cd $(FRONTEND_DIR) && $(NPM) run dev -- --host "$(HOST)" --port "$(WEB_PORT)" --strictPort'
	@echo "Web: http://$(HOST):$(WEB_PORT)"

dev-ui: kill-ui dev-api dev-web
	@sleep 2 && curl -sf http://$(HOST):$(PORT)/health >/dev/null 2>&1 || true
	@curl -sf http://$(HOST):$(WEB_PORT) >/dev/null 2>&1 || true

logs-api:
	@screen -r tensorscope-api

logs-web:
	@screen -r tensorscope-web

ui-status:
	@echo "Backend (port $(PORT)):"
	-@ss -ltnp | grep :$(PORT) || echo "  not listening"
	@echo "Frontend (port $(WEB_PORT)):"
	-@ss -ltnp | grep :$(WEB_PORT) || echo "  not listening"

add-resource:
	@test -n "$(RESOURCE_NAME)" || (echo "RESOURCE_NAME is required" && exit 1)
	@test -n "$(RESOURCE_URL)" || (echo "RESOURCE_URL is required" && exit 1)
	$(DATALAD) install -d . -D "$(RESOURCE_NAME)" -s "$(RESOURCE_URL)" "resources/$(RESOURCE_NAME)"

frontend-install:
	cd $(FRONTEND_DIR) && $(NPM) install

frontend-dev:
	cd $(FRONTEND_DIR) && $(NPM) run dev

frontend-build:
	cd $(FRONTEND_DIR) && $(NPM) run build

test:
	PYTHONPATH=src $(PYTHON) -m pytest tests -q

build:
	$(PYTHON) -m build

check:
	$(PYTHON) -m twine check dist/*

publish-test:
	$(PYTHON) -m twine upload --repository testpypi dist/*

publish:
	$(PYTHON) -m twine upload dist/*

clean:
	rm -rf build dist site .pytest_cache .mypy_cache src/*.egg-info src/tensorscope.egg-info
	rm -rf $(FRONTEND_DIR)/dist $(FRONTEND_DIR)/node_modules $(FRONTEND_DIR)/.vite

projio-init:
	$(PROJIO) init .

projio-config-user:
	$(PROJIO) config init-user

projio-config-show:
	$(PROJIO) config -C . show

projio-status:
	$(PROJIO) status -C .

projio-auth:
	$(PROJIO) auth -C . doctor

projio-gh:
	$(PROJIO) sibling -C . github

projio-gl:
	$(PROJIO) sibling -C . gitlab

projio-ria:
	$(PROJIO) sibling -C . ria

site-build:
	$(PROJIO) site build -C .

site-serve:
	$(PROJIO) site serve -C .

mcp:
	$(PROJIO) mcp -C .

-include .projio/projio.mk
