# generated by projio init
PYTHON ?= python
PROJIO ?= $(PYTHON) -m projio
NODE ?= node
NPM ?= npm
FRONTEND_DIR ?= frontend
DATA_PATH ?= data/demo_lfp.nc
HOST ?= 127.0.0.1
PORT ?= 8000

.PHONY: projio-init projio-config-user projio-config-show projio-status projio-auth
.PHONY: projio-gh projio-gl projio-ria site-build site-serve mcp
.PHONY: help dev demo-data dev-ui frontend-install frontend-dev frontend-build test build check publish-test publish clean

help:
	@printf '%s\n' \
		'make dev               # install editable package with dev extras' \
		'make demo-data         # generate a deterministic local demo dataset' \
		'make dev-ui            # run the TensorScope API and Vite dev server together' \
		'make frontend-install  # install frontend dependencies' \
		'make frontend-dev      # run Vite dev server' \
		'make frontend-build    # build the frontend bundle' \
		'make test              # run python tests' \
		'make build             # build wheel and sdist' \
		'make check             # run twine check on dist artifacts' \
		'make clean             # remove local build artifacts and caches' \
		'make projio-status     # show projio status'

dev:
	$(PYTHON) -m pip install -e ".[dev]"

demo-data:
	PYTHONPATH=src $(PYTHON) scripts/generate_demo_data.py --output "$(DATA_PATH)"

dev-ui:
	@sh -c 'PYTHONPATH=src $(PYTHON) -m tensorscope.cli serve "$(DATA_PATH)" --host "$(HOST)" --port "$(PORT)" & \
	api_pid=$$!; \
	trap "kill $$api_pid" EXIT INT TERM; \
	cd $(FRONTEND_DIR) && $(NPM) run dev'

frontend-install:
	cd $(FRONTEND_DIR) && $(NPM) install

frontend-dev:
	cd $(FRONTEND_DIR) && $(NPM) run dev

frontend-build:
	cd $(FRONTEND_DIR) && $(NPM) run build

test:
	PYTHONPATH=src $(PYTHON) -m pytest tests -q

build:
	$(PYTHON) -m build

check:
	$(PYTHON) -m twine check dist/*

publish-test:
	$(PYTHON) -m twine upload --repository testpypi dist/*

publish:
	$(PYTHON) -m twine upload dist/*

clean:
	rm -rf build dist site .pytest_cache .mypy_cache src/*.egg-info src/tensorscope.egg-info
	rm -rf $(FRONTEND_DIR)/dist $(FRONTEND_DIR)/node_modules $(FRONTEND_DIR)/.vite

projio-init:
	$(PROJIO) init .

projio-config-user:
	$(PROJIO) config init-user

projio-config-show:
	$(PROJIO) config -C . show

projio-status:
	$(PROJIO) status -C .

projio-auth:
	$(PROJIO) auth -C . doctor

projio-gh:
	$(PROJIO) sibling -C . github

projio-gl:
	$(PROJIO) sibling -C . gitlab

projio-ria:
	$(PROJIO) sibling -C . ria

site-build:
	$(PROJIO) site build -C .

site-serve:
	$(PROJIO) site serve -C .

mcp:
	$(PROJIO) mcp -C .
