# projio workspace config
project_name: tensorscope
project_kind: tool
description: ""

indexio:
  config: infra/indexio/config.yaml   # path to indexio config
  persist_dir: .projio/index           # chroma db location

biblio:
  enabled: true
  config: bib/config/biblio.yml

notio:
  enabled: true
  notes_dir: notes/

helpers:
  sibling:
    github:
      sibling: github
      credential: github
      project_template: "{project_name}"
    gitlab:
      sibling: gitlab
      credential: gitlab
      project_template: "{project_name}"
    ria:
      sibling: origin
      alias_strategy: basename
  docs:
    mkdocs:
      enabled: false
